FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip3 install --upgrade pip

RUN pip3 install -r ./requirements.txt --no-cache-dir

RUN pip3 install gunicorn

COPY . .

CMD ["gunicorn", "foodgram.wsgi:application", "--bind", "0:8000"]
